-- MySQL Script generated by MySQL Workbench
-- Wed Jul  6 14:13:27 2022
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inaf_prisma
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inaf_prisma` ;

-- -----------------------------------------------------
-- Schema inaf_prisma
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inaf_prisma` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `inaf_prisma` ;

-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_core_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_core_person` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_core_person` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `oid` VARCHAR(32) NULL,
  `username` VARCHAR(100) NULL,
  `password` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `title` VARCHAR(10) NULL,
  `first_name` VARCHAR(100) NULL,
  `middle_name` VARCHAR(100) NULL,
  `last_name` VARCHAR(100) NULL,
  `suffix` VARCHAR(10) NULL,
  `company` VARCHAR(100) NULL,
  `job_title` VARCHAR(100) NULL,
  `web_page_address` VARCHAR(100) NULL,
  `im_address` VARCHAR(100) NULL,
  `phone` VARCHAR(45) NULL,
  `address` VARCHAR(100) NULL,
  `postcode` VARCHAR(45) NULL,
  `number` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `timezone` VARCHAR(100) NULL DEFAULT 'Europe/London',
  `created_by` INT(11) NULL,
  `modified_by` INT(11) NULL,
  `assigned` INT(11) NULL,
  `is_station_referer` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `is_administrator` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `erased` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_node`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_node` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_node` (
  `code` VARCHAR(8) NOT NULL,
  `nickname` VARCHAR(100) NULL,
  `region_id` INT(11) UNSIGNED NOT NULL,
  `sequence_number` VARCHAR(3) NOT NULL COMMENT 'used to identify station under the same region.',
  `altitude` VARCHAR(100) NULL,
  `longitude` FLOAT(12,8) NULL,
  `latitude` FLOAT(12,8) NULL,
  `note` TEXT NULL,
  `IPaddress` VARCHAR(45) NULL,
  `MAC_address` VARCHAR(45) NULL,
  `hostname` VARCHAR(100) NULL,
  `active` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  `modified_by` INT(11) UNSIGNED NOT NULL,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `assigned` INT(11) UNSIGNED NOT NULL,
  `last_update` DATETIME NOT NULL,
  `nameof_company-association` VARCHAR(40) NULL,
  `address` VARCHAR(100) NULL,
  `postcode` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `province` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `refered_to` INT(11) UNSIGNED NULL DEFAULT 1,
  PRIMARY KEY (`code`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC),
  INDEX `fk_node_core_refered_idx` (`refered_to` ASC),
  CONSTRAINT `fk_node_core_refered`
    FOREIGN KEY (`refered_to`)
    REFERENCES `inaf_prisma`.`pr_core_person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_region` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_region` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `oid` VARCHAR(32) NULL,
  `state` VARCHAR(2) NOT NULL DEFAULT 'IT',
  `code` VARCHAR(2) NOT NULL,
  `name` VARCHAR(80) NOT NULL,
  `modified_by` INT(11) UNSIGNED NOT NULL,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `assigned` INT(11) UNSIGNED NOT NULL,
  `erased` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0,
  `last_update` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_drv_detection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_drv_detection` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_drv_detection` (
  `name` VARCHAR(50) NOT NULL,
  `node_code` VARCHAR(8) NULL,
  `abs_path` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `path_UNIQUE` (`abs_path` ASC),
  INDEX `fk_node_code_idx` (`node_code` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_node_code`
    FOREIGN KEY (`node_code`)
    REFERENCES `inaf_prisma`.`pr_node` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_drv_capture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_drv_capture` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_drv_capture` (
  `name` VARCHAR(50) NOT NULL,
  `node_code` VARCHAR(8) NULL,
  `abs_path` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `path_UNIQUE` (`abs_path` ASC),
  INDEX `fk_node_code_idx` (`node_code` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_node_code2`
    FOREIGN KEY (`node_code`)
    REFERENCES `inaf_prisma`.`pr_node` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_drv_calibration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_drv_calibration` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_drv_calibration` (
  `name` VARCHAR(50) NOT NULL,
  `node_code` VARCHAR(8) NULL,
  `abs_path` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NULL,
  `is_month` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `path_UNIQUE` (`abs_path` ASC),
  INDEX `fk_node_code_idx` (`node_code` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  CONSTRAINT `fk_node_code20`
    FOREIGN KEY (`node_code`)
    REFERENCES `inaf_prisma`.`pr_node` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_drv_event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_drv_event` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_drv_event` (
  `name` VARCHAR(50) NOT NULL,
  `abs_path` VARCHAR(100) NOT NULL,
  `datetime` DATETIME NULL,
  `is_processed` TINYINT(1) NULL DEFAULT 0,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `path_UNIQUE` (`abs_path` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `inaf_prisma`.`pr_drv_related`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inaf_prisma`.`pr_drv_related` ;

CREATE TABLE IF NOT EXISTS `inaf_prisma`.`pr_drv_related` (
  `event_name` VARCHAR(50) NOT NULL,
  `node_code` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`event_name`, `node_code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
