version: '3.7'
services:
  vpn:
    #https://github.com/kylemanna/docker-openvpn
    #https://github.com/kylemanna/docker-openvpn/blob/ea49a976fe4b131869319d1b5afc2738305f22d8/docs/docker-compose.md
    image: kylemanna/openvpn
    container_name: vpn
    cap_add:
     - NET_ADMIN
    ports:
     - "<PORT>:1194/udp"
    volumes:
     - </path/to/folder>:/etc/openvpn



