node('Linux') {  
	stage('Clone repository') {
        git credentialsId: 'novatia', url: 'https://github.com/n3srl/PRISMA_NODE_DOCKER.git', branch:'main'
    } 
    stage('Build image') {
       dir("orma-webmin"){
		dockerImage = docker.build("n3srl/orma-webmin:latest")
	   }
    }
    
	stage('Push image') {
        withDockerRegistry([ credentialsId: "n3_docker_hub", url: "" ]) {
			dockerImage.push()
        }
    }
}