FROM ubuntu:xenial

#ARG DEBIAN_FRONTEND=noninteractive

#downloads
RUN apt-get -y update 

#aravis
RUN apt-get install -y --no-install-recommends \
    intltool build-essential git

#freeture
RUN mkdir /usr/local/freeture-1.3.1
RUN git clone https://github.com/n3srl/freeture.git /usr/local/freeture/freeture_git

WORKDIR /usr/local/freeture-1.3.1/freeture_git/RUN chmod +x autogen.sh && ./autogen.sh && ./configure && make && make install

#set UTC timezone
ENV TZ 'UTC'
RUN echo $TZ > /etc/timezone && \
    apt-get install -y --no-install-recommends tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

#clear space
RUN rm -rf /var/lib/apt/lists/* && apt-get clean && apt-get autoremove -y

#add a configuration files
COPY ["configuration.cfg","/usr/local/share/freeture/"]

WORKDIR /freeture

ENTRYPOINT ["freeture"]
CMD ["-l"] 
