---
- name: Check SSH availability on guest_nodes
  hosts: guest_nodes
  gather_facts: yes
  tasks:
    - name: Check for SSH on port 22
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 1
      register: ssh_check
      ignore_errors: true

    - name: Extract IP addresses from the output string
      set_fact:
        ip_addresses: "{{ ssh_check | regex_findall('\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}') }}"

    - name: Add host to target_nodes
      add_host:
        name: "{{ inventory_hostname }}"
        groups: "target_nodes"
      loop: "{{ ip_addresses }}"
      
    - name: Debug ssh_check variable
      debug:
        var: ssh_check
            
    - name: Debug ip_addresses variable
      debug:
        var: ip_addresses
      
# This marks the end of the first play.
- name: Display all hosts in the 'target_nodes' group
  hosts: target_nodes
  gather_facts: no
  tasks:
    - name: Print hostname
      debug:
        msg: "{{ inventory_hostname }}"

#- import_playbook: update_freeture_on_nodes.yaml
