---
- name: Check SSH availability on guest_nodes
  hosts: guest_nodes
  gather_facts: yes
  tasks:
    - name: Check for SSH on port 22
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 1
      register: ssh_check
      ignore_errors: true


    - name: Print hostname
      debug:
        msg: "Hostname is {{ ansible_facts['hostname'] }}"

    - name: Add host to target_node
      add_host:
        name: "{{ inventory_hostname }}"
        groups: target_node

    - include_playbook: update_freeture_on_nodes.yaml
      vars:
        target_node: target_node
