---
- name: Check SSH availability on guest_nodes
  hosts: guest_nodes
  gather_facts: yes
  tasks:
    - name: Check for SSH on port 22
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 1
      register: ssh_check
      ignore_errors: true

    - name: Add host to target_nodes
      add_host:
        name: "{{ item.key }}"
        groups: "target_nodes"      
      loop: "{{ ssh_check | dict2items }}"
      
    - name: Debug ssh_check variable
      debug:
        var: ssh_check
      
# This marks the end of the first play.
- name: Display all hosts in the 'target_nodes' group
  hosts: target_nodes
  gather_facts: no
  tasks:
    - name: Print hostname
      debug:
        msg: "{{ inventory_hostname }}"

#- import_playbook: update_freeture_on_nodes.yaml
