---
- name: Update Docker containers on specified nodes
  hosts: guest_nodes
  become: no
  tasks:
    - name: Check for SSH on port 22
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 2
      register: ssh_check
      
    - name: Reset the repository to a specific state
      ansible.builtin.shell: |
        git reset --hard
      args:
        executable: /bin/bash
        chdir: /prismadata/orma-src 
        
    - name: Fetch latest changes from the main branch
      ansible.builtin.shell: |
        git fetch
      args:
        executable: /bin/bash
        chdir: /prismadata/orma-src 
        
    - name: Check current branch and switch to main if not on main
      ansible.builtin.shell: |
        git switch main
      args:
        executable: /bin/bash
        chdir: /prismadata/orma-src 
        
    - name: Pull latest changes from the main branch
      ansible.builtin.shell: |
        git pull
      args:
        executable: /bin/bash
        chdir: /prismadata/orma-src 
