version: '3.7'
services:
  vpn-client:
    image: lorenz10/openvpn-client
    container_name: prisma-vpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
    devices:
      - /dev/net/tun
    volumes:
      - type: volume
        source: vpn-conf
        target: /config/
    ports:
      - "8080:80"
      - "2222:2222"
  ssh-server:
    image: lorenz10/openssh-server
    container_name: prisma-ssh
    restart: unless-stopped
    network_mode: service:vpn-client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - SUDO_ACCESS=true
      - USER_NAME=prisma
      - PASSWORD_ACCESS=false
      #- USER_PASSWORD= -> passwordless sudo access
      - PUBLIC_KEY_FILE=/keys/rsa.pub
    volumes:
      - type: volume
        source: ssh-home
        target: /home/prisma/
      - type: volume
        source: freeture-conf
        target: /usr/local/share/freeture/
      - type: volume
        source: freeture-data
        target: /prismadata/
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock 
      - type: volume
        source: vpn-conf
        target: /etc/openvpn
    depends_on:
     - vpn-client
  orma:
    image: lorenz10/orma-webmin
    container_name: prisma-orma
    restart: unless-stopped
    network_mode: service:vpn-client
    volumes:
      - type: bind
        source: /todo
        target: /var/www/html
      - type: bind
        source: /todo
        target: /keys/chiave
      - type: bind
        source: /todo
        target: /keys/chiave.pub
    depends_on:
     - ssh-server
  freeture:
    image: freeture
    container_name: freeture
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - type: volume
        source: freeture-conf
        target: /usr/local/share/freeture/
      - type: volume
        source: freeture-data
        target: /freeture/
    command: ["-m","3"]
 
volumes:
  ssh-home:
    external: true
  freeture-conf:
    external: true
  freeture-data:
    external: true
  vpn-conf:
    external: true

#  ntp-client:
#    image: lorenz10/ntp-client
#    container_name: prisma-ntp
#    restart: unless-stopped
#    cap_add:
#      - SYS_TIME
#    depends_on:
#     - ssh-server