version: '3.7'
services:
  prisma-ssh:
    build: .
    image: n3srl/prisma-ssh
    logging:
      driver: json-file
      options:
        max-size: 512m
        max-file: 5
    container_name: prisma-ssh
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - type: volume
        source: orma-keys
        target: /keys/
      - type: bind
        source: /prismadata/data_share
        target: /prismadata
        read_only: true

volumes:
  orma-keys:
    external: true
